services:
  picarx-dt:
    build: .
    image: abarbie/picarx:${TAG:-latest}
    environment:
      - ROS_HOSTNAME=picarx-dt
      - ROS_MASTER_URI=http://picarx-dt:11313
      - ROS_HOST_PORT=11313
    tty: true
    ports:
      - 11313:11313
    command: roscore -p 11313
    healthcheck:
      test: [ "CMD-SHELL", "curl $${ROS_MASTER_URI} || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 1s

  mosquitto:
    container_name: mqtt-server
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./core/dtp/config:/root/catkin_ws/mosquitto
    command: mosquitto -c /root/catkin_ws/mosquitto/mosquitto.conf -p 1883
    depends_on:
      picarx-dt:
        condition: service_healthy

  picarx-gazebo:
    build:
      context: Dockerfile
      dockerfile: ./simulation
      target: desktop
      args:
        - TAG=${TAG:-latest}
    image: abarbie/picarx-gazebo:${TAG}
    env_file:
      - ./core/dtp/env/simulation.env
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_MASTER_URI=http://picarx-dt:11313
    tty: true
    volumes:
      - ./core:/root/catkin_ws/src/core
      - ./simulation:/root/catkin_ws/src/simulation
    command: /bin/bash -c "roslaunch picarx_gazebo picarx-world.launch & roslaunch picarx_control picarx_control.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  shadow-dt:
    image: abarbie/picarx:${TAG:-latest}
    env_file:
      - ./core/dtp/env/picarx-dt.env
    tty: true
    command: /bin/bash -c "roslaunch arches_core digitalshadow_dt.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  mqtt-dt:
    image: abarbie/picarx-arches-mqtt-bridge:${TAG}
    build:
      dockerfile: Dockerfile-arches-mqtt-bridge
      context: ./ros
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH:-}
    env_file:
      - ./core/dtp/env/picarx-dt.env
    command: /bin/bash -c "roslaunch arches_mqtt_bridge pt_client.launch host:=mqtt-server"
    depends_on:
      picarx:
        condition: service_healthy

  ackermann_skill-dt:
    image: abarbie/picarx-ackermann-skill:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/skills/ackermann_drive
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH:-}
    env_file:
      - ./core/dtp/env/picarx-dt.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - ${I2C:-/dev/i2c-0}:${I2C:-/dev/i2c-0}
      - ./core:/root/catkin_ws/src/core
      - ./ros/skills/ackermann_drive:/root/catkin_ws/src/skills/ackermann_drive
    command: /bin/bash -c "roslaunch picarx_ackermann_drive ackermann_skill.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  drive_monitor:
    build: ./ros/skills/ackermann_drive
    image: abarbie/picarx-ackermann-skill:${TAG}
    env_file:
      - ./core/dtp/env/picarx-dt.env
    tty: true
    privileged: true
    volumes:
      - ./core:/root/catkin_ws/src/core
      - ./ros/skills/ackermann_drive:/root/catkin_ws/src/skills/ackermann_drive
    command: /bin/bash -c "roslaunch picarx_ackermann_drive monitor_ds.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

networks:
  picarx:
    external: true
