services:
  picarx-core-build:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH}
    image: abarbie/picarx:${TAG:-latest}

networks:
  default:
    driver: bridge