services:
  picarx-dt:
    build: .
    image: abarbie/picarx:${TAG}
    environment:
      - ROS_HOSTNAME=picarx-dt
    tty: true
    ports:
      - 11313:11313
    command: roscore -p 11313
    healthcheck:
      test: [ "CMD-SHELL", "curl $${ROS_MASTER_URI} || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 1s

  mosquitto:
    container_name: mqtt-server
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./core/dtp/config:/root/catkin_ws/mosquitto
    command: mosquitto -c /root/catkin_ws/mosquitto/mosquitto.conf -p 1883
    depends_on:
      picarx-dt:
        condition: service_healthy

  shadow-dt:
    image: abarbie/picarx:${TAG}
    env_file:
      - ./core/dtp/env/picarx-dt.env
    tty: true
    command: /bin/bash -c "roslaunch arches_core digitalshadow_dt.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  mqtt-dt:
    image: abarbie/picarx/arches-mqtt-bridge:${TAG}
    build:
      dockerfile: Dockerfile-arches-mqtt-bridge
      context: ./ros
      args:
        - TAG=${TAG}
    env_file:
      - ./core/dtp/env/picarx-dt.env
    tty: true
    command: /bin/bash -c "roslaunch arches_mqtt_bridge dt_client.launch host:=mqtt-server"
    depends_on:
      picarx-dt:
        condition: service_healthy

  ackermann_skill-dt:
    image: abarbie/picarx/skills/ackermann_drive:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/skills/ackermann_drive
      args:
        - TAG=${TAG}
    env_file:
      - ./core/dtp/env/picarx-dt.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/skills/ackermann_drive:/root/catkin_ws/src/skills/ackermann_drive
    command: /bin/bash -c "
      roslaunch picarx_ackermann_drive ackermann_skill.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

networks:
  picarx:
    external: true