services:

  mosquitto:
    container_name: mqtt-server
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./core/dtp/config:/root/catkin_ws/mosquitto
    command: mosquitto -c /root/catkin_ws/mosquitto/mosquitto.conf -p 1883

  picarx:
    build: .
    image: abarbie/picarx:${TAG:-latest}
    environment:
      - ROS_HOSTNAME=picarxs
    tty: true
    ports:
      - 11311:11311
    command: roscore
    healthcheck:
      test: [ "CMD-SHELL", "curl $${ROS_MASTER_URI} || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 1s

  picarx-gazebo:
    image: abarbie/picarx-gazebo:${TAG}
    build:
      context: Dockerfile
      dockerfile: ./simulation
      target: desktop
      args:
        - TAG=${TAG:-latest}
    env_file:
      - ./core/dtp/env/simulation.env
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_HOSTNAME=picarx-gazebo
    tty: true
    ports:
      - 11312:11312
    volumes:
      - ./core:/root/catkin_ws/src/core
      - ./simulation:/root/catkin_ws/src/simulation
    command: /bin/bash -c "roslaunch picarx_gazebo picarx-world.launch & roslaunch picarx_control picarx_control.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  shadow-dtp:
    image: abarbie/picarx:${TAG:-latest}
    env_file:
      - ./core/dtp/env/picarx.env
    tty: true
    command: /bin/bash -c "roslaunch arches_core digitalshadow_dt.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  mqtt-dtp:
    image: abarbie/picarx-arches-mqtt-bridge:${TAG}
    build:
      dockerfile: Dockerfile-arches-mqtt-bridge
      context: ./ros
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH:-}
    env_file:
      - ./core/dtp/env/picarx.env
    tty: true
    command: /bin/bash -c "roslaunch arches_mqtt_bridge dt_client.launch host:=mqtt-server"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_left-dtp:
    build:
      dockerfile: Dockerfile
      context: ./ros/drivers/dcmotor/
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH:-}
    image: abarbie/picarx-dcmotor-driver:${TAG}
    env_file:
      - ./core/dtp/env/picarx.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - ${I2C:-/dev/i2c-0}:${I2C:-/dev/i2c-0}
      - ./core:/root/catkin_ws/src/core
      - ./ros/drivers/dcmotor:/root/catkin_ws/src/drivers/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_driver dcmotor_left.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_right-dtp:
    image: abarbie/picarx-dcmotor-driver:${TAG}
    tty: true
    env_file:
      - ./core/dtp/env/picarx.env
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - ${I2C:-/dev/i2c-0}:${I2C:-/dev/i2c-0}
      - ./core:/root/catkin_ws/src/core
      - ./ros/drivers/dcmotor:/root/catkin_ws/src/drivers/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_driver dcmotor_right.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  steering-dtp:
    image: abarbie/picarx-clutchgear-emulator:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/drivers/clutchgear
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH:-}
    env_file:
      - ./core/dtp/env/picarx.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - ${I2C:-/dev/i2c-0}:${I2C:-/dev/i2c-0}
      - ./core:/root/catkin_ws/src/core
      - ./ros/drivers/clutchgear:/root/catkin_ws/src/drivers/clutchgear
    command: /bin/bash -c "roslaunch picarx_clutchgear_driver ackermann_clutchgear_driver.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  ackermann_skill-dtp:
    image: abarbie/picarx-ackermann-skill:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/skills/ackermann_drive
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH:-}
    env_file:
      - ./core/dtp/env/picarx.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - ${I2C:-/dev/i2c-0}:${I2C:-/dev/i2c-0}
      - ./core:/root/catkin_ws/src/core
      - ./ros/skills/ackermann_drive:/root/catkin_ws/src/skills/ackermann_drive
    command: /bin/bash -c "roslaunch picarx_ackermann_drive ackermann_skill.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_emulator_left-dtp:
    image: abarbie/picarx-dcmotor-emulator:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/emulators/dcmotor
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH:-}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - ${I2C:-/dev/i2c-0}:${I2C:-/dev/i2c-0}
      - ./core:/root/catkin_ws/src/core
      - ./ros/emulators/dcmotor:/root/catkin_ws/src/emulators/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_emulator dcmotor_emulator_left.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_emulator_right-dtp:
    image: abarbie/picarx-dcmotor-emulator:${TAG}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - ${I2C:-/dev/i2c-0}:${I2C:-/dev/i2c-0}
      - ./core:/root/catkin_ws/src/core
      - ./ros/emulators/dcmotor:/root/catkin_ws/src/emulators/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_emulator dcmotor_emulator_right.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  steering_emulator-dtp:
    image: abarbie/picarx-clutchgear-emulator:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./ros/emulators/clutchgear
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH:-}
    env_file:
      - ./core/dtp/env/simulation.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - ${I2C:-/dev/i2c-0}:${I2C:-/dev/i2c-0}
      - ./core:/root/catkin_ws/src/core
      - ./ros/emulators/clutchgear:/root/catkin_ws/src/emulators/clutchgear
    command: /bin/bash -c "roslaunch picarx_clutchgear_emulator ackermann_clutchgear_emulator.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

networks:
  picarx:
    external: true
